name: .NET CI/CD WebApi

on:
  workflow_dispatch: 
  push:
    paths:
      - 'src-dotnet-webapi/**'

jobs:
  call-build:
    uses: ./.github/workflows/reusable-ci-dotnet.yaml
    with:
      app-path: ./src-dotnet-webapi
      package-type: "publish"

  deploy: 
    needs: call-build
    runs-on: ubuntu-latest    
    permissions: write-all
      # contents: read
      # packages: write      
    steps: 

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./output
      
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./output/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - uses: azure/setup-kubectl@v4          

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}      

      - uses: Azure/aks-set-context@v4
        with:
          cluster-name: aks-dojo-avanade
          resource-group: rg-dojo-avanade          

      - uses: Azure/k8s-create-secret@v5
        with:
          container-registry-url: ghcr.io
          container-registry-username: ${{ github.actor }}
          container-registry-password: ${{ secrets.GITHUB_TOKEN }}      
          secret-name: demo-k8s-secret          

      - uses: Azure/k8s-deploy@v5
        with:
          action: deploy
          manifests: |
            ./output/manifests/deployment.yaml
            ./output/manifests/service.yaml
          images: |
              ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          imagepullsecrets: |
            demo-k8s-secret          